version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -DfailIfNoTests=false
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/FoodAdda.jar
  discard-paths: yes
  