version: 0.2

env:
  variables:
    JAR_NAME: FoodAdda.jar
    S3_BUCKET: foodadda-deploy-artifacts
    EB_APP_NAME: foodaddaserver
    EB_ENV_NAME: Foodaddaserver-env

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - curl -sL https://downloads.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.zip -o maven.zip
      - unzip -q maven.zip
      - export MAVEN_HOME=$PWD/apache-maven-3.8.7
      - export PATH=$MAVEN_HOME/bin:$PATH
  build:
    commands:
      - echo Building the JAR...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed. Preparing to deploy...
      - VERSION_LABEL=$(date +%Y%m%d%H%M%S)
      - echo Uploading $JAR_NAME to S3...
      - aws s3 cp target/$JAR_NAME s3://$S3_BUCKET/$JAR_NAME
      - echo Creating new Elastic Beanstalk application version...
      - >
        aws elasticbeanstalk create-application-version
        --application-name $EB_APP_NAME
        --version-label "$VERSION_LABEL"
        --source-bundle S3Bucket="$S3_BUCKET",S3Key="$JAR_NAME"
      - echo Updating Elastic Beanstalk environment...
      - aws elasticbeanstalk update-environment --environment-name $EB_ENV_NAME --version-label "$VERSION_LABEL"

artifacts:
  files:
    - target/FoodAdda.jar
  discard-paths: true
