version: 0.2

env:
  variables:
    JAR_NAME: "FoodAdda.jar"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing AWS CLI if needed...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install || true

  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Uploading $JAR_NAME to S3...
      - aws s3 cp target/$JAR_NAME s3://foodadda-deploy-artifacts/$JAR_NAME
      - echo Creating application version...
      - VERSION_LABEL=$(date +%Y%m%d%H%M%S)
      - echo Using version label: $VERSION_LABEL
      - aws elasticbeanstalk create-application-version --application-name foodaddaserver --version-label "$VERSION_LABEL" --source-bundle S3Bucket="foodadda-deploy-artifacts",S3Key="$JAR_NAME"
      - echo Updating environment...
      - aws elasticbeanstalk update-environment --environment-name Foodaddaserver-env --version-label "$VERSION_LABEL"

artifacts:
  files:
    - target/FoodAdda.jar
