version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build complete.
      - echo Uploading JAR to S3...
      - aws s3 cp target/FoodAdda.jar s3://foodadda-deploy-artifacts/FoodAdda.jar
      - VERSION_LABEL=v1-`date +%Y%m%d%H%M%S`
      - echo Creating Elastic Beanstalk version $VERSION_LABEL...
      - aws elasticbeanstalk create-application-version \
          --application-name foodaddaserver \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket="foodadda-deploy-artifacts",S3Key="FoodAdda.jar"
      - echo Updating Elastic Beanstalk environment...
      - aws elasticbeanstalk update-environment \
          --environment-name Foodaddaserver-env \
          --version-label $VERSION_LABEL

artifacts:
  files:
    - target/FoodAdda.jar
